# -*- coding: utf-8 -*-
"""gemma 감정추출 최종 성공본

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-fCjmnQYCNe8AkP7RoS8XgO0lwgs2wGB

### 1. 필수 패키지 설치
분석 및 모델 구동에 필요한 라이브러리들을 설치합니다.
"""

import subprocess, sys

pkgs = [
    "numpy>=2.0",
    "transformers>=4.47.0",
    "bitsandbytes>=0.44.0",
    "accelerate>=0.34.0",
    "scikit-learn",
    "umap-learn",
    "matplotlib",
    "seaborn",
    "tqdm",
]

subprocess.check_call(
    [sys.executable, "-m", "pip", "install", "-q", "--upgrade"] + pkgs
)

print("\n✅ 설치 완료 — 필요한 경우 런타임을 재시작하세요.")

"""### 2. Hugging Face 인증
Gemma 모델을 사용하기 위해 Hugging Face Access Token이 필요합니다.
"""

from huggingface_hub import login
import getpass

# 토큰 입력창이 뜨면 본인의 HF 토큰을 입력하세요.
token = getpass.getpass("Enter your Hugging Face token: ")
if token:
    login(token=token)
else:
    print("토큰이 입력되지 않았습니다.")

"""### 3. 모델 및 토크나이저 로드 (4-bit Quantization)
Gemma-2-9B 모델을 효율적으로 사용하기 위해 NF4 4-bit 설정을 사용합니다.
"""

import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

MODEL_ID = "google/gemma-2-9b"

bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

print(f"Loading {MODEL_ID} in 4-bit NF4...")

tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_ID,
    quantization_config=bnb_config,
    device_map="auto",
    attn_implementation="eager",
)
model.eval()

n_layers = model.config.num_hidden_layers
hidden_dim = model.config.hidden_size
print(f"✓ Model loaded | layers={n_layers} hidden_dim={hidden_dim}")

# ================================================================
#  Emotion Concepts in Gemma-2-9B (Base)
#  모델 로드 이후 전체 코드
#  실행 순서대로 셀 구분: # ── CELL N ──
# ================================================================


# ── CELL 1 │ 라이브러리 & 설정 ──────────────────────────────────
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import seaborn as sns
import warnings
import torch
from tqdm.auto import tqdm
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import cross_val_score, cross_val_predict, StratifiedKFold
from sklearn.preprocessing import LabelEncoder, StandardScaler
from sklearn.metrics import confusion_matrix, classification_report

warnings.filterwarnings("ignore")
sns.set_theme(style="whitegrid", font_scale=1.1)

EMOTIONS = ["joy", "sadness", "fear", "anger", "disgust", "calm"]
EMOTION_COLORS = {
    "joy":     "#FFD700",
    "sadness": "#4169E1",
    "fear":    "#9B59B6",
    "anger":   "#DC143C",
    "disgust": "#27AE60",
    "calm":    "#17A589",
}
print("✓ 라이브러리 로드 완료")


# ── CELL 2 │ 감정 자극 프롬프트 ─────────────────────────────────
EMOTION_PROMPTS = {
    "joy": [
        "I just received the job offer I have been dreaming about for years. I am so",
        "My best friend surprised me with a birthday party. I felt completely",
        "After years of trying, we finally had a baby. I am overcome with",
        "The team won the championship and everyone was celebrating. I felt",
        "She said yes when I proposed and I was filled with",
        "I received the scholarship I needed to continue my education. I feel",
        "My cancer screening came back negative. I am so",
        "We adopted a puppy today and I am absolutely",
        "The performance was flawless and the crowd erupted. I felt",
        "After months apart, I finally reunited with my family and I was",
        "I completed my first marathon and crossed the finish line feeling",
        "My book got published today. I am incredibly",
        "I passed my driving test on the first attempt and I'm",
        "The flowers I planted finally bloomed and I feel",
        "I got the news that I had won the award. I am",
    ],
    "sadness": [
        "My dog passed away last night after 12 years together. I feel",
        "I didn't get into the university I worked so hard for. I am",
        "My parents are getting divorced and I feel",
        "I lost my job today after ten years of service. I am feeling",
        "I said goodbye to my best friend who is moving abroad. I feel",
        "The funeral was yesterday and I still can't believe they're gone. I am",
        "I found out my closest friend has been lying to me for years. I feel",
        "We had to let go of the house we grew up in. I'm",
        "She broke up with me after five years together. I feel so",
        "My grandfather forgot who I was today and I felt",
        "The project I spent months on was cancelled. I am",
        "My childhood pet had to be put to sleep. I'm feeling",
        "I realized I have wasted years on something that meant nothing. I feel",
        "I missed the chance to say goodbye before they died. I feel",
        "Everyone else moved on and I was left behind. I feel",
    ],
    "fear": [
        "I heard footsteps behind me in the dark alley. I felt",
        "The doctor said they found something concerning in my scan. I am",
        "The plane suddenly dropped several hundred feet. I was",
        "I saw a masked figure standing in the corner of my room. I felt",
        "The results of the biopsy were coming back tomorrow. I am",
        "We were alone on the highway when the car broke down at midnight. I felt",
        "There was a strange noise coming from the basement. I was",
        "I had to give a speech in front of 5000 people tomorrow. I felt",
        "The storm knocked out all the power and we couldn't see anything. I was",
        "Someone was following me home from the station. I felt",
        "I woke up and couldn't move my body at all. I felt",
        "We heard sirens and smelled smoke outside. I was",
        "My child didn't come home at the time they said. I am",
        "The bridge started swaying and I couldn't see the other side. I was",
        "I realized I might have made a catastrophic mistake. I am",
    ],
    "anger": [
        "My boss took credit for all of my work in the meeting. I was",
        "They cheated in the competition and still won the prize. I feel",
        "My neighbor has been parking in my spot for weeks. I am",
        "I was falsely accused in front of everyone. I feel",
        "They lied to me again after promising to change. I am",
        "The company raised prices but cut quality. I feel",
        "He interrupted me every time I tried to speak. I was",
        "They cancelled my flight without any compensation. I feel",
        "I found out I was paid less than my colleagues for the same work. I am",
        "Someone stole my work and published it as their own. I feel",
        "The referee made an obviously wrong call and I was",
        "My data was leaked due to their negligence. I am",
        "They broke their promise again at the last minute. I feel",
        "I was treated rudely by someone who had no reason to. I am",
        "He destroyed something irreplaceable out of spite. I felt",
    ],
    "disgust": [
        "I found mold growing all through the food I was about to eat. I felt",
        "The smell coming from the garbage was overwhelming. I was",
        "I saw what was in the meat before it was processed. I feel",
        "He continued eating loudly with his mouth open. I felt",
        "The conditions in the facility were filthy beyond belief. I was",
        "There was a cockroach in my food at the bottom of the bowl. I feel",
        "The bathroom hadn't been cleaned in months. I felt",
        "He made a comment that was deeply offensive and I was",
        "The wound had become infected and looked terrible. I felt",
        "I discovered what they put in the product. I am",
        "The way they treated the animals was absolutely",
        "I found something unexpected growing in the back of the fridge. I felt",
        "The behavior at the party was beyond inappropriate. I was",
        "They used completely unethical methods to win. I feel",
        "The smell of the chemical made me feel",
    ],
    "calm": [
        "I sat by the lake watching the still water at sunrise. I felt",
        "After the long day I finally settled into a warm bath. I am",
        "The meditation session left me feeling completely",
        "I walked slowly through the quiet forest and felt",
        "Everything was in order and nothing needed to be done. I felt",
        "I listened to the rain on the roof and felt",
        "The baby fell asleep peacefully and I felt",
        "I finished all my tasks early and sat in the garden. I feel",
        "The world was quiet and I had nowhere to be. I felt",
        "We sat together in comfortable silence. I felt",
        "Everything resolved itself without drama. I am",
        "The long journey was over and I was finally home. I felt",
        "The music played softly and everything felt",
        "I breathed deeply and let go of all tension. I felt",
        "There was nothing urgent left to do. I am",
    ],
}

total = sum(len(v) for v in EMOTION_PROMPTS.values())
print(f"✓ 프롬프트 준비: {total}개  ({total//len(EMOTIONS)}개 × {len(EMOTIONS)}감정)")


# ── CELL 3 │ Hidden State 추출 (~8분) ───────────────────────────
@torch.no_grad()
def extract_hidden_states(prompts, desc=""):
    results = []
    for prompt in tqdm(prompts, desc=desc, leave=False):
        inputs = tokenizer(prompt, return_tensors="pt",
                           truncation=True, max_length=128).to(model.device)
        out = model(**inputs, output_hidden_states=True, return_dict=True)
        last_tok = torch.stack(
            [h[0, -1, :].float().cpu() for h in out.hidden_states]
        )
        results.append(last_tok.numpy())
    return np.stack(results)   # (n_prompts, n_layers+1, hidden_dim)

emotion_acts = {}
labels_list, acts_list = [], []

for emo, prompts in EMOTION_PROMPTS.items():
    print(f"  ▶ {emo}", end="  ")
    acts = extract_hidden_states(prompts, desc=emo)
    emotion_acts[emo] = acts
    labels_list.extend([emo] * len(prompts))
    acts_list.append(acts)
    print(f"shape={acts.shape}  VRAM={torch.cuda.memory_allocated()/1e9:.2f}GB")

X_all = np.concatenate(acts_list, axis=0)
y_all = np.array(labels_list)
print(f"\n✓ X_all={X_all.shape}  y_all={y_all.shape}")


# ── CELL 4 │ Linear Probe (~3분) ────────────────────────────────
le  = LabelEncoder()
y_enc = le.fit_transform(y_all)
skf = StratifiedKFold(n_splits=5, shuffle=True, random_state=42)
n_layers_total = X_all.shape[1]

probe_accs = np.zeros(n_layers_total)
probe_stds = np.zeros(n_layers_total)

for layer_idx in tqdm(range(n_layers_total), desc="Probing layers"):
    X_s    = StandardScaler().fit_transform(X_all[:, layer_idx, :])
    scores = cross_val_score(
        LogisticRegression(max_iter=2000, C=1.0, n_jobs=-1),
        X_s, y_enc, cv=skf
    )
    probe_accs[layer_idx] = scores.mean()
    probe_stds[layer_idx] = scores.std()

best_layer = int(probe_accs.argmax())
chance     = 1.0 / len(EMOTIONS)
print(f"\n✓ Best layer: {best_layer}  |  Peak: {probe_accs[best_layer]*100:.1f}%  |  Chance: {chance*100:.1f}%")

# ── Probe Curve 시각화 ──
fig, ax = plt.subplots(figsize=(13, 4))
layers  = np.arange(n_layers_total)
ax.fill_between(layers, probe_accs - probe_stds, probe_accs + probe_stds,
                alpha=0.18, color="#2563EB")
ax.plot(layers, probe_accs, "o-", color="#2563EB", markersize=4,
        linewidth=2, label="Probe accuracy (5-fold CV)")
ax.axhline(chance, color="#94A3B8", linestyle="--", linewidth=1.5,
           label=f"Chance ({chance:.2f})")
ax.axvline(best_layer, color="#DC2626", linestyle="--", linewidth=1.5,
           label=f"Peak: Layer {best_layer}  ({probe_accs[best_layer]:.2f})")
ax.set_xlabel("Layer (residual stream position)", fontsize=12)
ax.set_ylabel("Accuracy", fontsize=12)
ax.set_title("Linear Probe: Emotion Classification Accuracy by Layer\n"
             "Gemma-2-9B Base", fontsize=13, fontweight="bold")
ax.yaxis.set_major_formatter(ticker.PercentFormatter(xmax=1, decimals=0))
ax.legend(fontsize=10)
ax.set_ylim(0, 1.05)
plt.tight_layout()
plt.savefig("fig1_probe_curve.png", dpi=150, bbox_inches="tight")
plt.show()


# ── CELL 5 │ 방향 벡터 추출 + 극성 교정 ─────────────────────────
def compute_directions(emotion_acts, layer_idx):
    """Difference-in-Means: d_e = normalize(mean_e - global_mean)"""
    all_vecs     = np.concatenate([a[:, layer_idx, :] for a in emotion_acts.values()], axis=0)
    global_mean  = all_vecs.mean(axis=0)
    directions   = {}
    for emo, acts in emotion_acts.items():
        diff = acts[:, layer_idx, :].mean(axis=0) - global_mean
        directions[emo] = diff / (np.linalg.norm(diff) + 1e-8)
    return directions

directions = compute_directions(emotion_acts, best_layer)
emos       = list(directions.keys())
hidden_dim_check = X_all.shape[-1]

# ── 극성 검증 & 자동 FLIP ──
print("\n방향 벡터 극성 검증")
print(f"{'감정':<10} {'자기 평균':>12} {'타 감정 평균':>14} {'상태':>16}")
print("─" * 58)

for emo in EMOTIONS:
    acts_emo   = emotion_acts[emo][:, best_layer, :]
    acts_other = np.concatenate([
        emotion_acts[e][:, best_layer, :] for e in EMOTIONS if e != emo
    ], axis=0)
    self_mean  = float((acts_emo   @ directions[emo]).mean())
    other_mean = float((acts_other @ directions[emo]).mean())
    ok         = self_mean > other_mean
    if not ok:
        directions[emo] = -directions[emo]
        status = "❌ 역방향 → FLIPPED"
    else:
        status = "✅ 정방향"
    print(f"  {emo:<10} {self_mean:>12.2f} {other_mean:>14.2f} {status:>16}")

# ── 방향 유사도 히트맵 ──
sim_mat = np.array([[np.dot(directions[e1], directions[e2])
                     for e2 in EMOTIONS] for e1 in EMOTIONS])

fig, ax = plt.subplots(figsize=(7, 6))
sns.heatmap(sim_mat,
            xticklabels=EMOTIONS, yticklabels=EMOTIONS,
            annot=True, fmt=".2f", cmap="RdBu_r",
            center=0, vmin=-1, vmax=1, ax=ax,
            annot_kws={"size": 12})
ax.set_title(f"Emotion Direction Cosine Similarity  (Layer {best_layer})",
             fontsize=12, fontweight="bold")
plt.tight_layout()
plt.savefig("fig2_direction_similarity.png", dpi=150, bbox_inches="tight")
plt.show()
print("✓ 방향 벡터 준비 완료")


# ── CELL 6 │ Confusion Matrix ────────────────────────────────────
X_best = X_all[:, best_layer, :]
X_s    = StandardScaler().fit_transform(X_best)
y_pred = cross_val_predict(
    LogisticRegression(max_iter=2000, C=1.0, n_jobs=-1),
    X_s, y_enc,
    cv=StratifiedKFold(5, shuffle=True, random_state=42)
)
y_pred_labels = le.inverse_transform(y_pred)
cm = confusion_matrix(y_all, y_pred_labels, labels=EMOTIONS, normalize="true")

fig, ax = plt.subplots(figsize=(8, 6))
sns.heatmap(cm, xticklabels=EMOTIONS, yticklabels=EMOTIONS,
            annot=True, fmt=".2f", cmap="Blues",
            vmin=0, vmax=1, ax=ax, linewidths=0.5,
            annot_kws={"size": 12})
ax.set_xlabel("Predicted", fontsize=12)
ax.set_ylabel("True", fontsize=12)
ax.set_title(
    f"Emotion Confusion Matrix  ·  Gemma-2-9B Base  ·  "
    f"Layer {best_layer}  ·  Acc={probe_accs[best_layer]*100:.1f}%",
    fontsize=12, fontweight="bold"
)
plt.tight_layout()
plt.savefig("fig3_confusion_matrix.png", dpi=150, bbox_inches="tight")
plt.show()
print(classification_report(y_all, y_pred_labels, target_names=EMOTIONS))


# ── CELL 7 │ Layer Scan → 감정별 최적 Steering Layer ────────────
@torch.no_grad()
def steer_single(prompt, direction, steer_layer, alpha, max_new_tokens=40):
    dir_t = torch.tensor(direction, dtype=torch.bfloat16).to(model.device)
    def hook_fn(module, inp, output):
        res = output[0] if isinstance(output, tuple) else output
        return (res + alpha * dir_t,) + output[1:] if isinstance(output, tuple) \
               else res + alpha * dir_t
    handle = model.model.layers[steer_layer].register_forward_hook(hook_fn)
    try:
        inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
        out = model.generate(**inputs, max_new_tokens=max_new_tokens,
                              do_sample=True, temperature=0.7,
                              pad_token_id=tokenizer.eos_token_id)
        return tokenizer.decode(out[0][inputs["input_ids"].shape[1]:],
                                skip_special_tokens=True)
    finally:
        handle.remove()

@torch.no_grad()
def all_emotion_scores(text, layer_idx):
    inputs = tokenizer(text, return_tensors="pt",
                       truncation=True, max_length=128).to(model.device)
    out = model(**inputs, output_hidden_states=True, return_dict=True)
    h   = out.hidden_states[layer_idx][0, -1, :].float().cpu().numpy()
    return {emo: float(np.dot(h, directions[emo])) for emo in EMOTIONS}

NEUTRAL         = "I opened the door and stepped outside. I"
SCAN_LAYERS     = list(range(10, n_layers, 4))
ALPHA_SCAN      = 100
baseline_scores = all_emotion_scores(NEUTRAL + " felt", best_layer)

scan_delta = {emo: [] for emo in EMOTIONS}

for layer_idx in tqdm(SCAN_LAYERS, desc="Layer scan"):
    for emo in EMOTIONS:
        txt = steer_single(NEUTRAL, directions[emo], layer_idx,
                           ALPHA_SCAN, max_new_tokens=25)
        sc  = all_emotion_scores(NEUTRAL + " " + txt, best_layer)[emo]
        scan_delta[emo].append(sc - baseline_scores[emo])

best_steer_layer = {
    emo: SCAN_LAYERS[int(np.argmax(vals))]
    for emo, vals in scan_delta.items()
}

# ── Layer Scan 시각화 ──
fig, ax = plt.subplots(figsize=(13, 5))
for emo in EMOTIONS:
    ax.plot(SCAN_LAYERS, scan_delta[emo], "o-",
            color=EMOTION_COLORS[emo], linewidth=2, markersize=5, label=emo)
ax.axhline(0, color="gray", linewidth=1, linestyle="--")
ax.set_xlabel("Steering Layer", fontsize=12)
ax.set_ylabel("Δ Direction Score (vs baseline)", fontsize=12)
ax.set_title(
    f"Emotion-Specific Optimal Steering Layer  (α={ALPHA_SCAN})\n"
    "각 감정 방향 벡터를 어느 레이어에 주입할 때 가장 효과적인가",
    fontsize=12, fontweight="bold"
)
ax.legend(fontsize=10)
plt.tight_layout()
plt.savefig("fig4_layer_scan.png", dpi=150, bbox_inches="tight")
plt.show()

print("\n감정별 최적 Steering Layer:")
for emo, lyr in best_steer_layer.items():
    print(f"  {emo:<10} → Layer {lyr:>2}  (Δ={scan_delta[emo][SCAN_LAYERS.index(lyr)]:.1f})")


# ── CELL 8 │ α 단조성 검증 (인과 유효성) ─────────────────────────
ALPHAS_MONO = [0, 50, 100, 150, 200, 250, 300]
mono_scores = {}

for emo in tqdm(EMOTIONS, desc="Monotonicity check"):
    lyr    = best_steer_layer[emo]
    deltas = []
    for alpha in ALPHAS_MONO:
        d   = directions[emo] if alpha > 0 else np.zeros(hidden_dim_check)
        txt = steer_single(NEUTRAL, d, lyr, alpha, max_new_tokens=30)
        sc  = all_emotion_scores(NEUTRAL + " " + txt, best_layer)[emo]
        deltas.append(sc - baseline_scores[emo])
    mono_scores[emo] = deltas

fig, axes = plt.subplots(2, 3, figsize=(15, 8), sharey=False)
axes = axes.flatten()

for i, emo in enumerate(EMOTIONS):
    ax     = axes[i]
    deltas = mono_scores[emo]
    color  = EMOTION_COLORS[emo]
    ax.plot(ALPHAS_MONO, deltas, "o-", color=color, linewidth=2.5, markersize=8)
    ax.fill_between(ALPHAS_MONO, 0, deltas, alpha=0.15, color=color)
    ax.axhline(0, color="gray", linewidth=1, linestyle="--")
    is_mono   = all(deltas[k] <= deltas[k+1] for k in range(len(deltas)-1))
    mono_tag  = "✅ 단조증가" if is_mono else "⚠️ 비단조"
    ax.set_title(f"{emo.upper()}  ({mono_tag})\nLayer {best_steer_layer[emo]}",
                 fontweight="bold", color=color, fontsize=11)
    ax.set_xlabel("α", fontsize=10)
    ax.set_ylabel("Δ Score", fontsize=10)
    ax.set_xticks(ALPHAS_MONO)
    ax.set_xticklabels(ALPHAS_MONO, rotation=45, fontsize=8)

fig.suptitle(
    "Activation Steering 인과 유효성 검증\n"
    "α 증가 → 목표 감정 방향 점수 단조증가 여부",
    fontsize=13, fontweight="bold"
)
plt.tight_layout()
plt.savefig("fig5_monotonicity.png", dpi=150, bbox_inches="tight")
plt.show()


# ── CELL 9 │ Cross-emotion Contamination Matrix ──────────────────
print("Cross-emotion contamination 계산 중... (36 forward passes)")

ALPHA_CROSS  = 300
cross_delta  = np.zeros((len(EMOTIONS), len(EMOTIONS)))
base_all     = all_emotion_scores(NEUTRAL + " felt", best_layer)

for i, inj_emo in enumerate(tqdm(EMOTIONS, desc="Injecting")):
    lyr = best_steer_layer[inj_emo]
    txt = steer_single(NEUTRAL, directions[inj_emo], lyr,
                       ALPHA_CROSS, max_new_tokens=35)
    sc  = all_emotion_scores(NEUTRAL + " " + txt, best_layer)
    for j, meas_emo in enumerate(EMOTIONS):
        cross_delta[i, j] = sc[meas_emo] - base_all[meas_emo]

fig, ax = plt.subplots(figsize=(9, 7))
sns.heatmap(cross_delta,
            xticklabels=[f"measure\n{e}" for e in EMOTIONS],
            yticklabels=[f"inject {e}" for e in EMOTIONS],
            annot=True, fmt=".1f", cmap="RdYlGn",
            center=0, linewidths=0.5, ax=ax,
            annot_kws={"size": 11})
for k in range(len(EMOTIONS)):
    ax.add_patch(plt.Rectangle((k, k), 1, 1,
                                fill=False, edgecolor="black", lw=2.5))
ax.set_title(
    f"Cross-Emotion Contamination Matrix  (α={ALPHA_CROSS})\n"
    "행 = 주입 감정  /  열 = 측정 점수 변화  /  ■ = 자기 감정",
    fontsize=11, fontweight="bold"
)
ax.set_xlabel("Measured emotion direction", fontsize=11)
ax.set_ylabel("Injected emotion", fontsize=11)
plt.tight_layout()
plt.savefig("fig6_cross_contamination.png", dpi=150, bbox_inches="tight")
plt.show()
print("대각 초록 → 자기 방향으로 이동 / off-diagonal 빨강 → 해당 감정 억압")


# ── CELL 10 │ Valence Axis 시각화 ───────────────────────────────
joy_dir = directions["joy"]
sad_dir = directions["sadness"]
X_best  = X_all[:, best_layer, :]

proj_joy = X_best @ joy_dir
proj_sad = X_best @ sad_dir

# steered 포인트 수집
steered_pts = {}
for emo in EMOTIONS:
    for alpha in [0, 200, 300]:
        d   = directions[emo] if alpha > 0 else np.zeros(hidden_dim_check)
        lyr = best_steer_layer[emo] if alpha > 0 else best_layer
        txt = steer_single(NEUTRAL, d, lyr, alpha, max_new_tokens=20)
        inputs = tokenizer(NEUTRAL + " " + txt, return_tensors="pt",
                           truncation=True, max_length=128).to(model.device)
        with torch.no_grad():
            out = model(**inputs, output_hidden_states=True, return_dict=True)
        h = out.hidden_states[best_layer][0, -1, :].float().cpu().numpy()
        steered_pts[(emo, alpha)] = (float(h @ joy_dir), float(h @ sad_dir))

fig, ax = plt.subplots(figsize=(11, 9))
scatter_kw = dict(alpha=0.35, s=60, edgecolors="white", linewidths=0.3)
for emo in EMOTIONS:
    mask = y_all == emo
    ax.scatter(proj_joy[mask], proj_sad[mask],
               color=EMOTION_COLORS[emo], **scatter_kw)

for emo in EMOTIONS:
    p0 = steered_pts[(emo, 0)]
    p2 = steered_pts[(emo, 200)]
    p3 = steered_pts[(emo, 300)]
    ax.scatter(*p0, marker="o", s=130, color=EMOTION_COLORS[emo],
               edgecolors="black", linewidths=1.5, zorder=5)
    ax.scatter(*p2, marker="^", s=170, color=EMOTION_COLORS[emo],
               edgecolors="black", linewidths=1.5, zorder=5)
    ax.scatter(*p3, marker="*", s=260, color=EMOTION_COLORS[emo],
               edgecolors="black", linewidths=1.5, zorder=5, label=emo)
    ax.annotate("", xy=p3, xytext=p0,
                arrowprops=dict(arrowstyle="->",
                                color=EMOTION_COLORS[emo], lw=1.8, alpha=0.7))

ax.axhline(0, color="gray", linewidth=0.6, linestyle="--", alpha=0.5)
ax.axvline(0, color="gray", linewidth=0.6, linestyle="--", alpha=0.5)

from matplotlib.lines import Line2D
legend_elems = [
    Line2D([0],[0], marker="o", color="gray", ms=7, label="α=0 (baseline)", ls="none"),
    Line2D([0],[0], marker="^", color="gray", ms=8, label="α=200", ls="none"),
    Line2D([0],[0], marker="*", color="gray", ms=10, label="α=300", ls="none"),
] + [Line2D([0],[0], marker="s", color=EMOTION_COLORS[e], ms=9,
            label=e, ls="none") for e in EMOTIONS]
ax.legend(handles=legend_elems, fontsize=9,
          bbox_to_anchor=(1.01, 1), loc="upper left")
ax.set_xlabel("Joy direction projection", fontsize=12)
ax.set_ylabel("Sadness direction projection", fontsize=12)
ax.set_title(
    "Valence Axis: Joy–Sadness 2D Emotion Space\n"
    f"원본 90개 샘플(투명) + Steering 궤적(화살표)  ·  Layer {best_layer}",
    fontsize=13, fontweight="bold"
)
plt.tight_layout()
plt.savefig("fig7_valence_axis.png", dpi=150, bbox_inches="tight")
plt.show()


# ── CELL 11 │ 최종 Steering 텍스트 데모 ─────────────────────────
DEMO_PROMPTS = [
    "When I think about what happened today, I feel",
    "Looking back at this week, my overall sense is",
    "I opened the door and stepped outside. I",
]
DEMO_ALPHAS = [0, 100, 200]

for prompt in DEMO_PROMPTS:
    print("=" * 72)
    print(f'  Prompt: "{prompt}"')
    print("=" * 72)
    for emo in EMOTIONS:
        print(f"\n  [{emo.upper()}]  Layer {best_steer_layer[emo]}")
        for alpha in DEMO_ALPHAS:
            d   = directions[emo] if alpha > 0 else np.zeros(hidden_dim_check)
            lyr = best_steer_layer[emo] if alpha > 0 else best_layer
            txt = steer_single(prompt, d, lyr, alpha, max_new_tokens=70)
            tag = f"α={alpha:>3}" if alpha > 0 else "base  "
            print(f"    {tag} │ {txt[:120]}")


# ── 최종 요약 ────────────────────────────────────────────────────
print("\n" + "=" * 72)
print("  EXPERIMENT COMPLETE")
print("=" * 72)
print(f"  Model            : google/gemma-2-9b  (4-bit NF4)")
print(f"  Best probe layer : {best_layer}")
print(f"  Peak accuracy    : {probe_accs[best_layer]*100:.1f}%  (chance={chance*100:.1f}%)")
print()
print("  감정별 최적 Steering Layer:")
for emo, lyr in best_steer_layer.items():
    print(f"    {emo:<10} → Layer {lyr:>2}")
print()
print("  저장된 Figure:")
for f in [
    "fig1_probe_curve.png",
    "fig2_direction_similarity.png",
    "fig3_confusion_matrix.png",
    "fig4_layer_scan.png",
    "fig5_monotonicity.png",
    "fig6_cross_contamination.png",
    "fig7_valence_axis.png",
]:
    print(f"    • {f}")
print("=" * 72)